import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, UserButton } from "@clerk/nextjs";
import { SignedOut } from "@clerk/nextjs/dist/types/components.server";
import { SignIn } from "@clerk/clerk-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          {children}
          <header className="flex-justify-between">
            <h1> Dashboard </h1>
            {/* <UserButton showName /> */}
          </header>
          <main>
            {/* <SignedOut>
              <SignIn routing="hash" />
            </SignedOut> */}
            <SignIn>{children}</SignIn>
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
